- name: Ensure /etc/systemd/system/docker.service.d directory exists
  file: 
    path: /etc/systemd/system/docker.service.d
    state: directory
    mode: 0755
  become: yes

- name: Copy systemd drop-in for Docker Mount Flags slave configuration
  copy:
    src: files/etc/systemd/system/docker.service.d/mountflags-slave.conf
    dest: /etc/systemd/system/docker.service.d/mountflags-slave.conf
  become: yes

