---
- name: Update APT cache block
  block:
    - name: Update APT cache
      when:
        - docker_network_access | bool
      become: true
      ansible.builtin.apt:
        update_cache: yes
        allow_unauthenticated: "{{ docker_allow_unauthenticated if ansible_pkg_mgr == 'apt' else omit }}"
      changed_when: false
      register: _pkg_result
      until: _pkg_result is succeeded
  rescue:
    - name: Retry APT cache update with allow-releaseinfo-change
      when:
        - docker_network_access | bool
      become: true
      ansible.builtin.command: apt-get update --allow-releaseinfo-change
      changed_when: false
      register: _pkg_result
      until: _pkg_result is succeeded
      tags:
        - skip_ansible_lint

- name: Ensure packages are installed for repository setup
  when:
    - docker_network_access | bool
    - docker_install_setup_repos_dependencies | bool
  become: true
  ansible.builtin.package:
    name: "{{ item }}"
    state: present
    allow_unauthenticated: "{{ docker_allow_unauthenticated if ansible_pkg_mgr == 'apt' else omit }}"
    disable_gpg_check: "{{ docker_disable_gpg_check if ansible_pkg_mgr in ['rpm', 'yum', 'dnf', 'dnf5', 'zypper'] else omit }}"
  loop: "{{ docker_repository_related_packages[_docker_os_dist_file_varity] }}"
  register: _pkg_result
  until: _pkg_result is succeeded

- name: Ensure packages are installed for repository setup (only for specific releases)
  when:
    - docker_network_access | bool
    - docker_install_setup_repos_dependencies | bool
    - (_docker_os_dist == "Debian" and _docker_os_dist_major_version | int < 13) or
      _docker_os_dist != "Debian"
  become: true
  ansible.builtin.package:
    name: "{{ item }}"
    state: present
    allow_unauthenticated: "{{ docker_allow_unauthenticated if ansible_pkg_mgr == 'apt' else omit }}"
    disable_gpg_check: "{{ docker_disable_gpg_check if ansible_pkg_mgr in ['rpm', 'yum', 'dnf', 'dnf5', 'zypper'] else omit }}"
  loop: "{{ docker_repository_related_packages_addons[_docker_os_dist_file_varity] }}"
  register: _pkg_result
  until: _pkg_result is succeeded

- name: Add Docker official GPG key (Ubuntu < 25 and Debian < 13)
  when:
    - docker_network_access | bool
    - (_docker_os_dist == "Ubuntu" and _docker_os_dist_major_version | int > 14 and _docker_os_dist_major_version | int < 25) or
      (_docker_os_dist == "Debian" and _docker_os_dist_major_version | int > 7 and  _docker_os_dist_major_version | int < 13)
  become: true
  ansible.builtin.apt_key:
    url: https://download.docker.com/linux/{{ _docker_os_dist | lower }}/gpg
    state: present
  register: _pkg_result
  until: _pkg_result is succeeded

- name: Download Docker GPG key (Ubuntu > 24 and Debian > 12)
  when:
    - docker_network_access | bool
    - (_docker_os_dist == "Ubuntu" and _docker_os_dist_major_version | int > 24) or
      (_docker_os_dist == "Debian" and _docker_os_dist_major_version | int > 12)
  become: true
  ansible.builtin.get_url:
    url: https://download.docker.com/linux/{{ _docker_os_dist | lower }}/gpg
    dest: /etc/apt/keyrings/docker.asc
    mode: '0644'
  register: _pkg_result
  until: _pkg_result is succeeded

- name: Determine channels to be enabled and/or disabled
  ansible.builtin.set_fact:
    _docker_enable_channels: "{{ docker_channels | intersect(_docker_merged_channels) }}"
  vars:
    _docker_mandatory_channel: []
    _docker_merged_channels: "{{ _docker_mandatory_channel + [docker_channel] }}"

- name: Add Docker CE repository with correct channels (Ubuntu < 25 and Debian < 13)
  become: true
  when:
    - (_docker_os_dist == "Ubuntu" and _docker_os_dist_major_version | int > 14 and _docker_os_dist_major_version | int < 25) or
      (_docker_os_dist == "Debian" and _docker_os_dist_major_version | int > 7 and  _docker_os_dist_major_version | int < 13)
  ansible.builtin.copy:
    content: >
      deb [arch={{ _docker_os_arch | lower }}] https://download.docker.com/linux/{{ _docker_os_dist | lower }}
      {{ _docker_os_dist_release }} {{ _docker_enable_channels | join(' ') }}
    dest: /etc/apt/sources.list.d/docker-ce.list
    owner: root
    group: root
    mode: '0644'

- name: Add Docker CE repository with correct channels (Ubuntu > 24 and Debian > 12)
  become: true
  when:
    - (_docker_os_dist == "Ubuntu" and _docker_os_dist_major_version | int > 24) or
      (_docker_os_dist == "Debian" and _docker_os_dist_major_version | int > 12)
  ansible.builtin.copy:
    content: >
      deb [arch={{ _docker_os_arch | lower }} signed-by=/etc/apt/keyrings/docker.asc] https://download.docker.com/linux/{{ _docker_os_dist | lower }}
      {{ _docker_os_dist_release }} {{ _docker_enable_channels | join(' ') }}
    dest: /etc/apt/sources.list.d/docker-ce.list
    owner: root
    group: root
    mode: '0644'
