---
- name: Update APT cache block
  block:
    - name: Update APT cache
      when:
        - docker_network_access | bool
      become: true
      ansible.builtin.apt:
        update_cache: yes
      changed_when: false
      register: _pkg_result
      until: _pkg_result is succeeded
  rescue:
    - name: Retry APT cache update with allow-releaseinfo-change
      when:
        - docker_network_access | bool
      become: true
      ansible.builtin.command: apt-get update --allow-releaseinfo-change
      changed_when: false
      register: _pkg_result
      until: _pkg_result is succeeded

- name: Ensure packages are installed for repository setup
  when:
    - docker_network_access | bool
  become: true
  ansible.builtin.package:
    name: "{{ item }}"
    state: present
  loop: "{{ docker_repository_related_packages[_docker_os_dist_file_varity] }}"
  register: _pkg_result
  until: _pkg_result is succeeded

- name: Add Docker official GPG key
  when:
    - docker_network_access | bool
    - (_docker_os_dist == "Ubuntu" and _docker_os_dist_major_version | int > 14) or
      (_docker_os_dist == "Debian" and _docker_os_dist_major_version | int > 7)
  become: true
  ansible.builtin.apt_key:
    url: https://download.docker.com/linux/{{ _docker_os_dist | lower }}/gpg
    state: present
  register: _pkg_result
  until: _pkg_result is succeeded

- name: Add Docker APT key (alternative for older Ubuntu systems without SNI).
  when:
    - docker_network_access | bool
    - (_docker_os_dist == "Ubuntu" and _docker_os_dist_major_version | int == 14) or
      (_docker_os_dist == "Debian" and  _docker_os_dist_major_version | int == 7)
  become: true
  ansible.builtin.shell: "curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo apt-key add -"
  changed_when: false
  tags:
    - skip_ansible_lint

- name: Determine channels to be enabled and/or disabled
  ansible.builtin.set_fact:
    _docker_disable_channels: "{{ docker_channels | difference(_docker_merged_channels) }}"
    _docker_enable_channels: "{{ docker_channels | intersect(_docker_merged_channels) }}"
  vars:
    _docker_mandatory_channel: []
    _docker_merged_channels: "{{ _docker_mandatory_channel + [docker_channel] }}"

- name: Add Docker CE repository with correct channels (Ubuntu/Debian)
  become: true
  ansible.builtin.copy:
    content: >
      deb [arch={{ _docker_os_arch | lower }}] https://download.docker.com/linux/{{ _docker_os_dist | lower }}
      {{ _docker_os_dist_release }} {{ _docker_enable_channels | join(' ') }}
    dest: /etc/apt/sources.list.d/docker-ce.list
    owner: root
    group: root
    mode: '0644'
