---
# vars file for ansible-role-docker-ce
docker_repository_related_rpm_packages:
  yum:
    - yum-utils
  dnf:
    # Includes dnf config-manager
    - dnf-plugins-core
  dnf5:
    # Includes dnf config-manager
    - dnf5-plugins

docker_repository_related_packages:
  RedHat: "{{ (ansible_pkg_mgr in ['yum','dnf','dnf5']) | ansible.builtin.ternary(docker_repository_related_rpm_packages[ansible_pkg_mgr], []) }}"
  Debian:
    - apt-transport-https
    - ca-certificates
    - curl
    - gnupg2
    - software-properties-common

docker_repository_url_rpm:
  RedHat: https://download.docker.com/linux/rhel/docker-ce.repo
  CentOS: https://download.docker.com/linux/centos/docker-ce.repo
  Fedora: https://download.docker.com/linux/fedora/docker-ce.repo

docker_channels:
  - stable
  - nightly
  - test

docker_cmd_enable_disable_rpm_repo:
  yum: yum-config-manager --{{ (_item_enabled == true) | ternary('enable', 'disable') }} docker-ce-{{ item }}
  dnf: dnf config-manager --set-{{ (_item_enabled == true) | ternary('enabled', 'disabled') }} docker-ce-{{ item }}
  dnf5: dnf config-manager setopt docker-ce-{{ item }}.enabled={{ (_item_enabled == true) | ternary('1', '0') }}

docker_cmd_update_rpm_repo_cache:
  yum: yum makecache
  dnf: dnf makecache
  dnf5: dnf makecache

docker_cmd_update_repo_cache:
  RedHat: "{{ (ansible_pkg_mgr in ['yum','dnf','dnf5']) | ansible.builtin.ternary(docker_cmd_update_rpm_repo_cache[ansible_pkg_mgr], []) }}"
  Debian: apt-get update

docker_envs_dir:
  RedHat: /etc/sysconfig
  Debian: /etc/default

docker_packages:
  - docker-ce-cli
  - docker-ce
  - containerd.io
  - docker-buildx-plugin
  - docker-compose-plugin

docker_os_pkg_version_separator:
  RedHat: "-"
  Debian: "="

docker_old_packages:
  RedHat:
    - docker
    - docker-client
    - docker-client-latest
    - docker-common
    - docker-latest
    - docker-latest-logrotate
    - docker-logrotate
    - docker-selinux
    - docker-engine-selinux
    - docker-engine
    - docker-rhel-*-plugin
  Debian:
    - docker
    - docker-engine
    - docker.io
    - containerd
    - runc

docker_python2_build_os_pkgs:
  Debian:
    - python-dev
    - libffi-dev
    - libssl-dev
  Fedora:
    - python-devel
    - openssl-devel
    - redhat-rpm-config
    - libffi-devel
  RedHat:
    - python-devel
    - openssl-devel

docker_python3_build_os_pkgs:
  Debian:
    - libffi-dev
    - libssl-dev
  Fedora:
    - python3-devel
    - openssl-devel
    - redhat-rpm-config
    - libffi-devel
  RedHat:
    - python3-devel
    - openssl-devel

docker_predefined_packages_os:
  Debian:
    sdk:
      - python3-docker
    stack:
      - python3-jsondiff
      - python3-yaml

docker_predefined_packages_pip:
  RedHat:
    sdk:
      - docker{{'<5' if ansible_python_version is version('3', '<') }}
    stack:
      - jsondiff
      - pyyaml

docker_cli_plugins_dir:
  RedHat: /usr/libexec/docker/cli-plugins
  Debian: /usr/libexec/docker/cli-plugins
